[build]
  command = "npm install && npm run build:full"
  publish = "client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle API requests
[[redirects]]
  from = "/api/*"
  to = "/server/index.js"
  status = 200 